# This is a basic workflow to help you get started with Actions

name: Build-sphinx-docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  # This workflow contains a single job called "build"
  build: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
           python-version: "3.8"

      # Install dependencies to build the docs
      - name: Install dependencies
        run: | 
          cd docs/
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Build html pages from .rst source files
      - name: Build HTML
        run: | 
          cd docs/
          make html

      # index.html must be at the root of the docs/ directory
      - name: Link index.html  
        run: | 
          cd docs/
          echo '<meta http-equiv="refresh" content="0; url=./_build/html/index.html"/>' > index.html
      
      # Add empty .nojekyll file at the root of the docs/ directory to enable using sphinx rtd theme
      - name: Add .nojekyll 
        run: |
          cd docs/
          touch .nojekyll